name: 测试Bot登陆

on:
  workflow_dispatch:

jobs:
  ruff:
    name: 测试Bot登陆
    runs-on: ubuntu-latest
    concurrency:
      group: trapedit-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Run Actions
        run: |
          uv run src/__init__.py testlogin \
            --username "$USERNAME" \
            --password "$PASSWORD"
        shell: bash
        env:
          USERNAME: "${{ secrets.GH_BOT_USERNAME }}"
          PASSWORD: "${{ secrets.GH_BOT_PASSWORD }}"