name: Update New Traps

on:
  workflow_dispatch:

jobs:
  ruff:
    name: Update New Traps
    runs-on: ubuntu-latest
    concurrency:
      group: trapedit-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Clone GameData
        run: |
          sudo mkdir /home/bot
          cd /home/bot
          sudo git clone https://github.com/Kengxxiao/ArknightsGameData.git --depth 1

      - name: Run Actions
        run: |
          uv run src/__init__.py trapstage \
            --username "$USERNAME" \
            --password "$PASSWORD"
        shell: bash
        env:
          PAGE: "${{ github.event.inputs.page }}"
          USERNAME: "${{ secrets.GH_BOT_USERNAME }}"
          PASSWORD: "${{ secrets.GH_BOT_PASSWORD }}"